export const CONFIG = {
    apiKey: "AQ.Ab8RN6KCILCKQYf1mqY27b22HzVpjHDDvKeOL1fcAblbQPw3dA",
    secretSalt: "HD_SAMHO_SECURE_KEY_2026_!@#",
    firebase: {
        apiKey: "AIzaSyCxUZLBx9zRhUK-5RRsRp4UPujyOrvDsfg",
        authDomain: "hd-visa-system.firebaseapp.com",
        projectId: "hd-visa-system",
        storageBucket: "hd-visa-system.firebasestorage.app",
        messagingSenderId: "635228928760",
        appId: "1:635228928760:web:5293bd988de4bfa1c9590d"
    },
    appId: 'visa-app'
};

export const reqNames = {
    'chk_alien_reg': '외국인 등록', 
    'chk_extension': '체류기간 연장허가', 
    'chk_change_work': '근무처 변경/추가',
    'chk_reentry': '재입국허가', 
    'chk_reissue': '등록증 재발급', 
    'chk_change_status': '체류자격 변경'
};

export const docMatrix = {
    'E-9': {
        'chk_alien_reg': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '거주/숙소제공 확인서', en: 'Proof of Residence Form', vn: 'Giấy chứng minh nơi ở' }, type: 'auto' },
            { name: { kr: '여권 원본', en: 'Original Passport', vn: 'Hộ chiếu gốc' }, type: 'personal' },
            { name: { kr: '표준규격사진 1매', en: '1 Standard Photo', vn: '1 Ảnh tiêu chuẩn' }, type: 'personal' },
            { name: { kr: '마약검사확인서', en: 'Drug Test Certificate', vn: 'Giấy khám ma túy' }, type: 'personal' },
            { name: { kr: '사업자 등록증 사본', en: 'Business Registration Certificate', vn: 'Giấy phép kinh doanh' }, type: 'company' },
            { name: { kr: '고용허가서 사본', en: 'Copy of Employment Permit', vn: 'Bản sao Giấy phép LĐ' }, type: 'company' },
            { name: { kr: '표준근로계약서 사본', en: 'Copy of Standard Labor Contract', vn: 'Bản sao Hợp đồng LĐ' }, type: 'company' }
        ],
        'chk_extension': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '거주/숙소제공 확인서', en: 'Proof of Residence Form', vn: 'Giấy chứng minh nơi ở' }, type: 'auto' },
            { name: { kr: '여권', en: 'Passport', vn: 'Hộ chiếu' }, type: 'personal' },
            { name: { kr: '외국인 등록증', en: 'Alien Registration Card (ARC)', vn: 'Thẻ cư trú (ARC)' }, type: 'personal' },
            { name: { kr: '고용허가서 사본', en: 'Copy of Employment Permit', vn: 'Bản sao Giấy phép LĐ' }, type: 'company' },
            { name: { kr: '표준근로계약서 사본', en: 'Copy of Standard Labor Contract', vn: 'Bản sao Hợp đồng LĐ' }, type: 'company' },
            { name: { kr: '사업자 등록증 사본', en: 'Business Registration Certificate', vn: 'Giấy phép kinh doanh' }, type: 'company' }
        ],
        'chk_change_work': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '거주/숙소제공 확인서', en: 'Proof of Residence Form', vn: 'Giấy chứng minh nơi ở' }, type: 'auto' },
            { name: { kr: '여권', en: 'Passport', vn: 'Hộ chiếu' }, type: 'personal' },
            { name: { kr: '외국인 등록증', en: 'Alien Registration Card (ARC)', vn: 'Thẻ cư trú (ARC)' }, type: 'personal' },
            { name: { kr: '고용허가서 사본', en: 'Copy of Employment Permit', vn: 'Bản sao Giấy phép LĐ' }, type: 'company' },
            { name: { kr: '표준근로계약서 사본', en: 'Copy of Standard Labor Contract', vn: 'Bản sao Hợp đồng LĐ' }, type: 'company' },
            { name: { kr: '사업자 등록증 사본', en: 'Business Registration Certificate', vn: 'Giấy phép kinh doanh' }, type: 'company' }
        ],
        'chk_reentry': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '여권', en: 'Passport', vn: 'Hộ chiếu' }, type: 'personal' },
            { name: { kr: '외국인등록증', en: 'Alien Registration Card (ARC)', vn: 'Thẻ cư trú (ARC)' }, type: 'personal' }
        ],
        'default': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '여권 및 외국인 등록증', en: 'Passport & ARC', vn: 'Hộ chiếu & Thẻ cư trú' }, type: 'personal' }
        ]
    },
    'E-7': {
        'chk_extension': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '신원보증서', en: 'Original Guarantee Form', vn: 'Bản gốc Giấy bảo lãnh' }, type: 'auto' },
            { name: { kr: '거주/숙소제공 확인서', en: 'Proof of Residence Form', vn: 'Giấy chứng minh nơi ở' }, type: 'auto' },
            { name: { kr: '여권 및 외국인 등록증', en: 'Passport & ARC', vn: 'Hộ chiếu & Thẻ cư trú' }, type: 'personal' },
            { name: { kr: '개인 소득금액 증명', en: 'Proof of Personal Income', vn: 'Chứng minh thu nhập cá nhân' }, type: 'personal' },
            { name: { kr: '고용계약서', en: 'Employment Contract', vn: 'Hợp đồng lao động' }, type: 'company' },
            { name: { kr: '사업장 등록증 사본', en: 'Business/Corporate Registration', vn: 'Giấy phép KD' }, type: 'company' },
            { name: { kr: '고용주 납세증명서 등', en: 'Employer Tax Certificates', vn: 'Chứng nhận nộp thuế' }, type: 'company' }
        ],
        'chk_change_work': [
            { name: { kr: '통합신청서', en: 'Integrated Application Form', vn: 'Đơn xin tổng hợp' }, type: 'auto' },
            { name: { kr: '여권 및 외국인 등록증', en: 'Passport & ARC', vn: 'Hộ chiếu & Thẻ cư trú' }, type: 'personal' },
            { name: { kr: '고용추천서', en: 'Employment Recommendation', vn: 'Thư giới thiệu việc làm' }, type: 'company' },
            { name: { kr: '고용계약서', en: 'Employment Contract', vn: 'Hợp đồng lao động' }, type: 'company' },
            { name: { kr: '사업자등록증', en: 'Business Registration', vn: 'Giấy phép kinh doanh' }, type: 'company' }
        ],
        'chk_reentry': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '여권 원본', en: 'Original Passport', vn: 'Hộ chiếu gốc' }, type: 'personal' },
            { name: { kr: '외국인 등록증', en: 'Alien Registration Card (ARC)', vn: 'Thẻ cư trú (ARC)' }, type: 'personal' },
            { name: { kr: '수수료', en: 'Processing Fee', vn: 'Lệ phí' }, type: 'personal' }
        ],
        'chk_change_status': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '신원보증서', en: 'Original Guarantee Form', vn: 'Bản gốc Giấy bảo lãnh' }, type: 'auto' },
            { name: { kr: '거주/숙소제공 확인서', en: 'Proof of Residence Form', vn: 'Giấy chứng minh nơi ở' }, type: 'auto' },
            { name: { kr: '여권 및 외국인 등록증', en: 'Passport & ARC', vn: 'Hộ chiếu & Thẻ cư trú' }, type: 'personal' },
            { name: { kr: '개인 소득금액 증명', en: 'Proof of Personal Income', vn: 'Chứng minh thu nhập cá nhân' }, type: 'personal' },
            { name: { kr: '자격 요건 입증 서류', en: 'Proof of Qualifications', vn: 'Giấy tờ chứng minh trình độ' }, type: 'personal' },
            { name: { kr: '고용계약서 및 사업자등록증', en: 'Contract & Business Registration', vn: 'Hợp đồng LĐ & GPKD' }, type: 'company' }
        ],
        'default': [
            { name: { kr: '통합신청서', en: 'Application Form', vn: 'Đơn đăng ký' }, type: 'auto' },
            { name: { kr: '여권 및 외국인 등록증', en: 'Passport & ARC', vn: 'Hộ chiếu & Thẻ cư trú' }, type: 'personal' }
        ]
    }
};

export const i18nDict = {
    'kr': {
        'header_title': 'HD현대삼호 비자지원', 
        'btn_db': '클라우드 명부', 
        'btn_settings': '설정',
        'home_title': '외국인 통합 비자지원 시스템', 
        'home_desc': '간단한 정보 입력만으로 출입국 필수 서류가 양식에 맞춰 자동 완성됩니다.', 
        'home_start': '개인 신청(1인 접수)', 
        'home_excel': '관리자 신청(다수 접수)',
        's1_step': 'Step 1', 
        's1_title': '비자 및 민원 선택', 
        's1_desc': '선택하신 내용에 따라 필요한 입력 항목과 증빙 서류가 동적으로 변경됩니다.',
        's1_visa': '보유 비자 자격', 
        's1_req': '민원 종류 (신청/신고)',
        'req_1': '외국인 등록', 
        'req_2': '체류기간 연장허가', 
        'req_3': '근무처 변경/추가', 
        'req_4': '재입국허가', 
        'req_5': '등록증 재발급', 
        'req_6': '체류자격 변경',
        'btn_next_step': '다음 단계 진행하기', 
        'btn_to_excel': '엑셀 파일 업로드 단계로',
        's_excel_step': 'Step 2 (Batch)', 
        's_excel_title': '다수 인원 일괄 처리', 
        's_excel_desc': 'Step 1에서 선택한 <b>기본 설정값</b> 외에도<br>엑셀 칸을 클릭하면 V 체크 항목들을 리스트에서 편하게 선택할 수 있습니다.',
        'btn_excel_down': '표준 템플릿 다운로드', 
        'btn_excel_up': '작성된 엑셀 업로드 (생성 시작)', 
        'msg_excel_prog': '수십 명의 PDF를 압축 생성 중입니다. 잠시만 기다려주세요...',
        's2_step': 'Step 2', 
        's2_title': '외국인 인적사항', 
        'btn_camera': '사진 촬영', 
        'btn_gallery': '파일 첨부',
        's2_sub1': '기본 인적 정보',
        'l_surname': '성 (Surname)', 
        'l_givenname': '명 (Given Name)', 
        'l_dob': '생년월일 (YYYY-MM-DD)', 
        'l_gender': '성별',
        'gender_m': '남성(M)', 
        'gender_f': '여성(F)', 
        'l_nation': '국적 (Nationality)', 
        'l_arc': '외국인등록번호', 
        'l_pass': '여권번호 (Passport No.)', 
        'l_pass_date': '여권 발급일 / 만료일',
        's2_sub2': '신청서 제출자', 
        'sub_self': '본인 직접 제출', 
        'sub_spouse': '배우자 (대리)', 
        'sub_parents': '부/모 (대리)',
        'l_spouse': '배우자 성명 영문', 
        'l_parents': '부/모 성명 영문',
        'btn_prev': '이전', 
        'btn_next': '다음 단계',
        's3_step': 'Step 3', 
        's3_title': '주소 및 연락처',
        's3_sub1': '대한민국 체류지 정보', 
        'l_addr_kr': '현재 대한민국 내 주소', 
        'l_cell': '휴대전화번호', 
        'l_tel': '일반 전화번호 (선택)',
        's3_sub2': '본국 (Home Country) 정보', 
        'l_addr_home': '본국 주소 (Home Address)', 
        'l_home_tel': '본국 전화번호', 
        'l_email': '전자우편 (E-mail)',
        's4_step': 'Step 4', 
        's4_title': '근무처 및 거주 정보',
        's4_sub1': '원 근무처 정보', 
        'l_cname': '근무처 명칭', 
        'l_cregno': '사업자등록번호', 
        'l_rep_name': '대표자 성명', 
        'l_rep_id': '대표자 주민번호', 
        'l_rep_gender': '대표자 성별', 
        'l_caddr': '회사 주소', 
        'l_cphone': '회사 전화번호',
        's4_sub2': '예정 근무처 정보', 
        'l_new_cname': '예정 근무처 명칭', 
        'l_new_cregno': '사업자등록번호', 
        'l_new_cphone': '전화번호',
        's4_sub3': '거주/숙소 제공 정보', 
        'l_dorm_own': '숙소 소유 형태', 
        'own_1': '자가', 
        'own_2': '임대', 
        'own_3': '기타',
        'l_dorm_type': '숙소 주거 형태', 
        'type_1': '기숙사', 
        'type_2': '개인주택', 
        'type_3': '숙박시설', 
        'l_dorm_start': '제공 시작일 (입주일)',
        's4_sub4': '기타 신고 정보', 
        'l_job': '근로자 직업', 
        'l_income': '연소득 (단위: 만원)', 
        'l_reentry': '재입국 신청 기간', 
        'l_refund': '수수료 환급 계좌',
        'l_guar_date': '신원보증 기간 (From - To)',
        'btn_to_ai': 'AI 검증 단계로',
        's5_step': 'Step 5', 
        's5_title': 'AI 서류 정밀 검증',
        's5_sub1': 'AI 증빙서류 교차 검증', 
        's5_badge': '동적 매핑 활성화', 
        's5_desc': '증빙서류를 여러 번 나누어 촬영/업로드하셔도 AI가 하나로 취합하여 정밀 대조합니다.',
        's5_btn_camera': '문서 직접 촬영',
        's5_btn_gallery': '갤러리 / PDF',
        'btn_verify': '서류 교차 검증 시작', 
        'btn_edit': '입력 수정', 
        'btn_skip': '건너뛰고 서류 생성',
        's6_step': 'Step 6', 
        's6_title': '최종 서류 생성', 
        's6_desc': '입력하신 정보 기반으로 완성된 서류를 확인하고 다운로드하세요.',
        's6_sub1': '생성할 문서 선택', 
        'doc_1': '통합신청서 (별지 제34호)', 
        'doc_2': '거주/숙소제공 확인서', 
        'doc_3': '신원보증서 (별지 제129호)',
        'btn_generate': '선택된 서류 일괄 생성', 
        'btn_back_to_ai': '이전 단계로 가기',
        'ai_pass_title': '검증 완료: 100% 일치합니다.', 
        'ai_pass_desc': '단 하나의 모순도 발견되지 않았습니다.', 
        'ai_fail_title': '불일치 발견',
        'ai_msg_fail_title': '입력 수정 필요', 
        'ai_msg_fail_desc': 'AI가 불일치를 발견했습니다.\n이전 화면으로 돌아가 붉게 깜빡이는 테두리의 입력칸을 수정해주세요.',
        'ai_msg_err_title': 'AI 통신 오류', 
        'ai_msg_err_desc': '검증 서버 연결에 실패했습니다.\n서류 생성 단계는 정상 진행 가능합니다.', 
        'btn_ai_recheck': '다시 대조하기', 
        'ai_loading': '초정밀 교차 대조 분석 중...',
        'btn_to_step7': '다음 단계 (최종 제출 점검)',
        's7_step': 'Step 7', 
        's7_title': '최종 준비 서류 점검', 
        's7_desc': '해당 민원에 필요한 모든 서류가 준비되었는지 확인해 주세요.',
        's7_success_title': '모든 서류 준비 완료!',
        's7_success_desc': '모든 서류가 꼼꼼하게 준비되었습니다.<br>관할 출입국·외국인관서에 방문하시거나 하이코리아(온라인)를 통해 신청을 완료해 주시기 바랍니다.',
        'btn_home': '처음으로 돌아가기',
        'badge_auto': '이 시스템 자동생성',
        'badge_company': '회사 발급',
        'badge_personal': '개인 준비(작성)'
    },
    'en': {
        'btn_db': 'Cloud DB', 
        'btn_settings': 'Settings',
        'home_title': 'Integrated Visa Support System', 
        'home_desc': 'A simple input automatically completes required immigration documents according to the format.', 
        'home_start': 'Single Application', 
        'home_excel': 'Batch Processing',
        's1_step': 'Step 1', 
        's1_title': 'Visa & Request Type', 
        's1_desc': 'Fields will change dynamically based on your selection.',
        's1_visa': 'Current Visa', 
        's1_req': 'Request Type',
        'req_1': 'Alien Registration', 
        'req_2': 'Extension of Stay', 
        'req_3': 'Change of Workplace', 
        'req_4': 'Re-entry Permit', 
        'req_5': 'Re-issuance', 
        'req_6': 'Change of Status',
        'btn_next_step': 'Proceed to Next Step', 
        'btn_to_excel': 'Go to Excel Upload',
        's_excel_step': 'Step 2 (Batch)', 
        's_excel_title': 'Batch Processing', 
        's_excel_desc': 'The template features dropdowns for easy selection.<br>Download the template, fill it out, and upload it.',
        'btn_excel_down': 'Download Standard Template', 
        'btn_excel_up': 'Upload Filled Excel (Start)', 
        'msg_excel_prog': 'Generating dozens of PDFs into a ZIP... Please wait.',
        's2_step': 'Step 2', 
        's2_title': 'Personal Info', 
        'btn_camera': 'Take Photo', 
        'btn_gallery': 'Upload File',
        's2_sub1': 'Basic Info',
        'l_surname': 'Surname', 
        'l_givenname': 'Given Name', 
        'l_dob': 'Date of Birth', 
        'l_gender': 'Gender',
        'gender_m': 'Male(M)', 
        'gender_f': 'Female(F)', 
        'l_nation': 'Nationality', 
        'l_arc': 'ARC Number', 
        'l_pass': 'Passport No.', 
        'l_pass_date': 'Issue / Expiry Date',
        's2_sub2': 'Application Submitter', 
        'sub_self': 'Self', 
        'sub_spouse': 'Spouse (Proxy)', 
        'sub_parents': 'Parents (Proxy)',
        'l_spouse': 'Spouse Name', 
        'l_parents': 'Parents Name',
        'btn_prev': 'Back', 
        'btn_next': 'Next',
        's3_step': 'Step 3', 
        's3_title': 'Address & Contact',
        's3_sub1': 'Address in Korea', 
        'l_addr_kr': 'Current Address', 
        'l_cell': 'Cell Phone', 
        'l_tel': 'Telephone',
        's3_sub2': 'Home Country Info', 
        'l_addr_home': 'Home Address', 
        'l_home_tel': 'Home Phone', 
        'l_email': 'E-mail',
        's4_step': 'Step 4', 
        's4_title': 'Workplace & Residence Info',
        's4_sub1': 'Current Workplace', 
        'l_cname': 'Company Name', 
        'l_cregno': 'Business Reg. No.', 
        'l_rep_name': 'Representative', 
        'l_rep_id': 'Rep. ID No.', 
        'l_rep_gender': 'Rep. Gender', 
        'l_caddr': 'Company Address', 
        'l_cphone': 'Company Phone',
        's4_sub2': 'New Workplace', 
        'l_new_cname': 'New Company Name', 
        'l_new_cregno': 'Business Reg. No.', 
        'l_new_cphone': 'Phone',
        's4_sub3': 'Accommodation Info', 
        'l_dorm_own': 'Ownership Type', 
        'own_1': 'Owned', 
        'own_2': 'Rented', 
        'own_3': 'Other',
        'l_dorm_type': 'Housing Type', 
        'type_1': 'Dormitory', 
        'type_2': 'Private House', 
        'type_3': 'Hotel/Motel', 
        'l_dorm_start': 'Moving-in Date',
        's4_sub4': 'Other Info', 
        'l_job': 'Worker\'s Occupation', 
        'l_income': 'Annual Income', 
        'l_reentry': 'Re-entry Period', 
        'l_refund': 'Refund Account',
        'l_guar_date': 'Guarantee Period (From-To)',
        'btn_to_ai': 'Go to AI Check',
        's5_step': 'Step 5', 
        's5_title': 'AI Verification',
        's5_sub1': 'AI Document Cross-Check', 
        's5_badge': 'Dynamic Mapping', 
        's5_desc': 'You can take multiple photos, and AI will compile and check them together.',
        's5_btn_camera': 'Take Document Photo',
        's5_btn_gallery': 'Gallery / PDF',
        'btn_verify': 'Start AI Verification', 
        'btn_edit': 'Edit Info', 
        'btn_skip': 'Skip & Generate',
        's6_step': 'Step 6', 
        's6_title': 'Final Document Generation', 
        's6_desc': 'Check the completed documents based on your input and download them.',
        's6_sub1': 'Select Documents to Generate', 
        'doc_1': 'Application Form (No.34)', 
        'doc_2': 'Accommodation Form', 
        'doc_3': 'Guarantee Form (No.129)',
        'btn_generate': 'Generate Documents', 
        'btn_back_to_ai': 'Back',
        'ai_pass_title': 'Verification Complete: 100% Match.', 
        'ai_pass_desc': 'No discrepancies were found.', 
        'ai_fail_title': 'Discrepancies Found',
        'ai_msg_fail_title': 'Input Correction Needed', 
        'ai_msg_fail_desc': 'AI found discrepancies.\nPlease go back and edit the highlighted fields.',
        'ai_msg_err_title': 'AI Communication Error', 
        'ai_msg_err_desc': 'Failed to connect to the verification server.\nYou can still proceed to document generation.', 
        'btn_ai_recheck': 'Re-verify', 
        'ai_loading': 'Performing cross-check...',
        'btn_to_step7': 'Next Step (Final Checklist)',
        's7_step': 'Step 7', 
        's7_title': 'Final Document Checklist', 
        's7_desc': 'Please confirm all required documents are ready.',
        's7_success_title': 'All Documents Ready!',
        's7_success_desc': 'All documents are perfectly prepared.<br>Please visit the immigration office or apply online via HiKorea.',
        'btn_home': 'Go to Home',
        'badge_auto': 'System Auto-generated',
        'badge_company': 'Company Provided',
        'badge_personal': 'Personal Prep'
    },
    'vn': {
        'btn_db': 'Hồ sơ Đám mây', 
        'btn_settings': 'Cài đặt',
        'home_title': 'Hệ thống hỗ trợ Visa tích hợp', 
        'home_desc': 'Thông tin đơn giản sẽ tự động điền các tài liệu cần thiết.', 
        'home_start': 'Tạo đơn cá nhân', 
        'home_excel': 'Xử lý hàng loạt',
        's1_step': 'Bước 1', 
        's1_title': 'Loại Visa & Yêu cầu', 
        's1_desc': 'Các trường sẽ thay đổi dựa trên lựa chọn của bạn.',
        's1_visa': 'Visa hiện tại', 
        's1_req': 'Loại yêu cầu',
        'req_1': 'Đăng ký người NN', 
        'req_2': 'Gia hạn lưu trú', 
        'req_3': 'Đổi nơi làm việc', 
        'req_4': 'Phép tái nhập cảnh', 
        'req_5': 'Cấp lại', 
        'req_6': 'Đổi tư cách',
        'btn_next_step': 'Tiếp tục', 
        'btn_to_excel': 'Đến bước tải lên Excel',
        's_excel_step': 'Bước 2 (Hàng loạt)', 
        's_excel_title': 'Xử lý hàng loạt', 
        's_excel_desc': 'Tải mẫu Excel xuống. Bạn có thể dễ dàng lựa chọn các trường trong file Excel.',
        'btn_excel_down': 'Tải mẫu Excel chuẩn', 
        'btn_excel_up': 'Tải lên Excel đã điền (Bắt đầu)', 
        'msg_excel_prog': 'Đang tạo hàng tá PDF vào tệp ZIP... Vui lòng đợi.',
        's2_step': 'Bước 2', 
        's2_title': 'Thông tin cá nhân', 
        'btn_camera': 'Chụp ảnh', 
        'btn_gallery': 'Tải tệp lên',
        's2_sub1': 'Thông tin cơ bản',
        'l_surname': 'Họ (Surname)', 
        'l_givenname': 'Tên (Given Name)', 
        'l_dob': 'Ngày sinh', 
        'l_gender': 'Giới tính',
        'gender_m': 'Nam(M)', 
        'gender_f': 'Nữ(F)', 
        'l_nation': 'Quốc tịch', 
        'l_arc': 'Số thẻ cư trú', 
        'l_pass': 'Số hộ chiếu', 
        'l_pass_date': 'Ngày cấp / Hết hạn',
        's2_sub2': 'Người nộp đơn', 
        'sub_self': 'Bản thân', 
        'sub_spouse': 'Vợ/Chồng', 
        'sub_parents': 'Bố/Mẹ',
        'l_spouse': 'Tên vợ/chồng', 
        'l_parents': 'Tên bố/mẹ',
        'btn_prev': 'Quay lại', 
        'btn_next': 'Tiếp theo',
        's3_step': 'Bước 3', 
        's3_title': 'Địa chỉ & Liên hệ',
        's3_sub1': 'Địa chỉ tại Hàn Quốc', 
        'l_addr_kr': 'Địa chỉ hiện tại', 
        'l_cell': 'Số điện thoại', 
        'l_tel': 'Điện thoại bàn',
        's3_sub2': 'Thông tin quê nhà', 
        'l_addr_home': 'Địa chỉ quê nhà', 
        'l_home_tel': 'SĐT quê nhà', 
        'l_email': 'Email',
        's4_step': 'Bước 4', 
        's4_title': 'Thông tin Nơi làm việc & Chỗ ở',
        's4_sub1': 'Nơi làm việc', 
        'l_cname': 'Tên công ty', 
        'l_cregno': 'Mã số kinh doanh', 
        'l_rep_name': 'Người đại diện', 
        'l_rep_id': 'CMND đại diện', 
        'l_rep_gender': 'Giới tính ĐD', 
        'l_caddr': 'Địa chỉ công ty', 
        'l_cphone': 'SĐT công ty',
        's4_sub2': 'Nơi làm việc mới', 
        'l_new_cname': 'Tên công ty mới', 
        'l_new_cregno': 'Mã số kinh doanh', 
        'l_new_cphone': 'Số điện thoại',
        's4_sub3': 'Thông tin chỗ ở', 
        'l_dorm_own': 'Loại sở hữu', 
        'own_1': 'Tự sở hữu', 
        'own_2': 'Thuê', 
        'own_3': 'Khác',
        'l_dorm_type': 'Loại nhà ở', 
        'type_1': 'Ký túc xá', 
        'type_2': 'Nhà riêng', 
        'type_3': 'Khách sạn/Nhà nghỉ', 
        'l_dorm_start': 'Ngày chuyển đến',
        's4_sub4': 'Thông tin khác', 
        'l_job': 'Nghề nghiệp của công nhân', 
        'l_income': 'Thu nhập năm', 
        'l_reentry': 'Thời gian tái nhập cảnh', 
        'l_refund': 'Tài khoản hoàn tiền',
        'l_guar_date': 'Thời gian bảo lãnh (Từ - Đến)',
        'btn_to_ai': 'Đến bước kiểm tra AI',
        's5_step': 'Bước 5', 
        's5_title': 'Xác minh AI',
        's5_sub1': 'Đối chiếu Tài liệu AI', 
        's5_badge': 'Bản đồ động', 
        's5_desc': 'Bạn có thể chụp nhiều ảnh, AI sẽ tổng hợp và đối chiếu.',
        's5_btn_camera': 'Chụp tài liệu',
        's5_btn_gallery': 'Thư viện / PDF',
        'btn_verify': 'Bắt đầu kiểm tra AI', 
        'btn_edit': 'Sửa thông tin', 
        'btn_skip': 'Bỏ qua & Tạo',
        's6_step': 'Bước 6', 
        's6_title': 'Tạo tài liệu cuối cùng', 
        's6_desc': 'Kiểm tra các tài liệu đã hoàn thành dựa trên đầu vào của bạn và tải xuống.',
        's6_sub1': 'Chọn Mẫu', 
        'doc_1': 'Đơn đăng ký (Mẫu 34)', 
        'doc_2': 'Giấy xác nhận chỗ ở', 
        'doc_3': 'Giấy bảo lãnh (Mẫu 129)',
        'btn_generate': 'Tạo tài liệu đã chọn', 
        'btn_back_to_ai': 'Quay lại',
        'ai_pass_title': 'Xác minh hoàn tất: Khớp 100%.', 
        'ai_pass_desc': 'Không tìm thấy sự mâu thuẫn nào.', 
        'ai_fail_title': 'Phát hiện không khớp',
        'ai_msg_fail_title': 'Cần sửa đầu vào', 
        'ai_msg_fail_desc': 'AI phát hiện thông tin không khớp.\nVui lòng quay lại và sửa các trường được bôi đỏ.',
        'ai_msg_err_title': 'Lỗi kết nối AI', 
        'ai_msg_err_desc': 'Không thể kết nối với máy chủ xác minh.\nBạn vẫn có thể tiếp tục tạo tài liệu.', 
        'btn_ai_recheck': 'Kiểm tra lại', 
        'ai_loading': 'Đang phân tích đối chiếu...',
        'btn_to_step7': 'Tiếp theo (Kiểm tra cuối cùng)',
        's7_step': 'Bước 7', 
        's7_title': 'Danh sách tài liệu cuối cùng', 
        's7_desc': 'Vui lòng xác nhận tất cả tài liệu đã sẵn sàng.',
        's7_success_title': 'Tất cả tài liệu đã sẵn sàng!',
        's7_success_desc': 'Tất cả tài liệu đã được chuẩn bị đầy đủ.<br>Vui lòng đến văn phòng xuất nhập cảnh hoặc nộp trực tuyến qua HiKorea.',
        'btn_home': 'Về trang chủ',
        'badge_auto': 'Hệ thống tự động tạo',
        'badge_company': 'Công ty cấp',
        'badge_personal': 'Cá nhân chuẩn bị'
    }
};
